"""
report_writer.py
────────────────
Section 4 – Sample Incident Report Generation.

Responsibilities:
  • Select the most interesting (highest-confidence non-benign) alert.
  • Render a complete, structured Markdown incident report.
  • Write the report to REPORTS_DIR/sample_incident_report.md.

This file is the document submitted separately with the exercise.
"""

import alert_generator
import alert_generator
import textwrap
from datetime import datetime, timezone
from pathlib import Path

import config


# ─────────────────────────────────────────────────────────────────────────────
# Sample selection
# ─────────────────────────────────────────────────────────────────────────────

def pick_best_sample(alerts: list[dict]) -> int:
    """
    Return the index of the highest-confidence non-benign alert.
    Falls back to index 0 if all samples are benign.
    """
    best_idx, best_conf = 0, -1.0
    for i, alert in enumerate(alerts):
        cls  = alert["predicted_threat"]["class_name"]
        conf = alert["predicted_threat"]["confidence"]
        if cls != "Benign" and conf > best_conf:
            best_conf, best_idx = conf, i
    return best_idx


# ─────────────────────────────────────────────────────────────────────────────
# Markdown rendering helpers
# ─────────────────────────────────────────────────────────────────────────────

def _safe(enrichment: dict, key: str, fallback: str = "N/A") -> str:
    val = enrichment.get(key, fallback)
    return str(val).strip() if val else fallback


def _alternatives_table(alternatives: list[dict]) -> str:
    if not alternatives:
        return "_No alternative predictions available._"
    header = "| Class       | Probability |\n|-------------|-------------|"
    rows   = "\n".join(
        f"| {a['class_name']:11s} | {a['probability']*100:.2f}%       |"
        for a in alternatives
    )
    return f"{header}\n{rows}"


def _observations_table(obs: dict) -> str:
    if not obs:
        return "_No network observations available._"
    header = "| Feature | Value |\n|---------|-------|"
    rows   = "\n".join(f"| `{k}` | `{v}` |" for k, v in obs.items())
    return f"{header}\n{rows}"


def _severity_icon(reasonable: bool) -> str:
    return "✅ Reasonable" if reasonable else "⚠️ Questionable"


def _match_icon(match: bool) -> str:
    return "✅ Matched" if match else "⚠️ Not clearly matched"


def _hallucination_icon(count: int, detail: str) -> str:
    if count == 0:
        return "✅ None detected"
    return f"⚠️ {count} detected: {detail}"


# ─────────────────────────────────────────────────────────────────────────────
# Main rendering function
# ─────────────────────────────────────────────────────────────────────────────

def render_incident_report(
    alert:    dict,
    report:   dict,
    ev_row:   dict,
) -> str:
    """
    Return the full Markdown text of the incident report.
    """
    enrich    = report["llm_enrichment"]
    meta      = enrich.get("_llm_meta", {})
    cls_name  = alert["predicted_threat"]["class_name"]
    confidence = alert["predicted_threat"]["confidence"]
    severity  = _safe(enrich, "severity", "UNKNOWN")
    gen_time  = meta.get("generation_time_s", "N/A")
    llm_model = meta.get("model", config.LLM_MODEL)
    ollama_ok = meta.get("ollama_available", False)

    llm_note = (
        f"Generated by **{llm_model}** via Ollama (local, offline) in **{gen_time}s**."
        if ollama_ok else
        f"⚠️ Ollama was not available during generation. Enrichment fields are "
        f"heuristic placeholders. Re-run with `ollama serve` and `{llm_model}` "
        f"pulled for real LLM output."
    )

    comp = alert.get("affected_network_component", {})
    expected_sev_str = ", ".join(sorted(config.EXPECTED_SEVERITY.get(cls_name, {"UNKNOWN"})))

    return textwrap.dedent(f"""\
    # CTI Incident Report

    **Report ID**      : {report['report_id']}
    **Alert ID**       : {alert['alert_id']}
    **Detection Time** : {alert['detection_timestamp']}
    **Generated**      : {datetime.now(timezone.utc).isoformat()}

    ---

    ## 1. Executive Summary

    The network intrusion detection system flagged a network flow as **{cls_name}**
    with a confidence of **{confidence*100:.2f}%** (XGBoost classifier, F1-macro ≈ 0.89).
    The assigned severity level is **{severity}**.

    > {llm_note}

    ---

    ## 2. Detection Details

    | Field           | Value                              |
    |-----------------|------------------------------------|
    | Predicted Class | **{cls_name}**                     |
    | Confidence      | {confidence*100:.2f}%              |
    | Model           | XGBoost (200 estimators, depth 7)  |
    | Severity        | {severity}                         |
    | Human Review    | {_safe(enrich, 'human_review_required')} |

    ### Alternative Predictions

    {_alternatives_table(alert.get('alternative_predictions', []))}

    ---

    ## 3. Network Observations

    {_observations_table(alert.get('network_observations', {}))}

    ### Affected Network Component

    | Field          | Value                                                  |
    |----------------|--------------------------------------------------------|
    | Source IP      | {comp.get('source_ip', 'N/A')}                        |
    | Destination IP | {comp.get('destination_ip', 'N/A')}                   |
    | Protocol       | {comp.get('protocol', 'N/A')}                         |
    | Description    | {comp.get('description', 'N/A')}                      |

    ---

    ### 4. LLM CTI Enrichment

    > **LLM Configuration**
    > - Model: `{llm_model}`
    > - Deployment: Ollama (local, offline, zero cost, no API key)
    > - Temperature: {config.LLM_TEMPERATURE}  |  Max tokens: {config.LLM_MAX_TOKENS}
    > - Generation time: {gen_time}s

    ### 4.1 Threat Context

    {_safe(enrich, 'threat_context')}

    ### 4.2 Attack Correlation

    {_safe(enrich, 'attack_correlation')}

    ### 4.3 Possible Impact

    {_safe(enrich, 'possible_impact')}

    ### 4.4 Immediate Response

    {_safe(enrich, 'immediate_response')}

    ### 4.5 Long-Term Mitigation

    {_safe(enrich, 'long_term_mitigation')}

    ### 4.6 Human Review

    **Required:** {_safe(enrich, 'human_review_required')}

    {_safe(enrich, 'human_review_justification')}

    ---


    """)


# ─────────────────────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────────────────────

def generate_incident_report(
    alerts:    list[dict],
    reports:   list[dict],
    eval_rows: list[dict],
) -> Path:
    """
    Pick the most interesting sample, render the Markdown report, and save it.

    Returns:
        Path to the written report file.
    """
    config.REPORTS_DIR.mkdir(parents=True, exist_ok=True)

    print("\n" + "=" * 60)
    print("SECTION 4: Writing sample incident report …")
    
    idx    = pick_best_sample(alerts)
    md     = render_incident_report(alerts[idx], reports[idx], eval_rows[idx])
    path   = config.REPORTS_DIR / f"sample_incident_report_{idx}.md"
    path.write_text(md, encoding="utf-8")

    cls    = alerts[idx]["predicted_threat"]["class_name"]
    conf   = alerts[idx]["predicted_threat"]["confidence"]
    print(f"  ✔ Incident report written  ({cls}, {conf*100:.1f}% conf)")
    print(f"     → {path}")
    return path
